# Generated by Django 4.2.6 on 2023-10-21 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='кличка')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='фото')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='ДР')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'собака',
                'verbose_name_plural': 'собаки',
                'ordering': ('name', 'author'),
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='кличка')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='ДР')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.dog', verbose_name='собака')),
            ],
            options={
                'verbose_name': 'предок',
                'verbose_name_plural': 'предки',
            },
        ),
    ]
