# Generated by Django 4.2.6 on 2023-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_dog_is_public_alter_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(default=10, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
