# Generated by Django 4.2.6 on 2023-11-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_dog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='цена'),
        ),
    ]
