# Generated by Django 4.2.6 on 2023-11-16 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelter', '0005_alter_dog_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='likes',
            field=models.ManyToManyField(related_name='likes_dogs', to=settings.AUTH_USER_MODEL, verbose_name='автор лайка'),
        ),
    ]
