version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres
    restart: always
    env_file:
      - .env

    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
#     если указана PGDATA, то в вольюмс прописываем путь до /var/lib/postgresql/data/pgdata, если PGDATA нет то заканчиваем на data
#      #- PGUSER=postgres

    volumes:
#      - pg_data:/var/lib/postgresql/data
      - pg_data:/var/lib/postgresql/data/pgdata

    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
#      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
#    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    command: bash -c "python manage.py migrate && python manage.py csu && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8001:8000'
    volumes:
      - .:/code

    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
#    command: bash -c "celery -A config worker -l INFO -P eventlet"
#    tty: true
    command: bash -c "python.exe -m celery -A config worker -l INFO -P eventlet"
    depends_on:
      - redis
      - app

volumes:
  pg_data: